### ISSUE TITLE
tdqm

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [cgarciae/pypeln#21]
Hello! First of all, amazing library, I am a huge fan. I was wondering how can I add  tdqm (https://github.com/tqdm/tqdm) to pypeln to see the progress.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @suzil , thank you a lot!

**Comment by cgarciae** [comment]
@FrancescoSaverioZuppichini Thanks!
@suzil I often do it like this :
```python
stage = pr.map(my_func, data, workers=3)
result = list( x for x in tqdm(stage, total=data.shape[0]))
```

**Comment by suzil** [comment]
@cgarciae looks cleaner than mine! Thanks.

**Comment by FrancescoSaverioZuppichini** [comment]
@cgarciae Perfect, it looks awesome ;)
