### ISSUE TITLE
Version 0.4.0+ doesn't work on Python 3.6

### ISSUE THREAD

**Issue by nosmoke** [cgarciae/pypeln#41]
You have added "from typing import Protocol" in the latest versions, and Protocol is not available in Python before version 3.8.
This is breaking some of our code that runs on Python 3.6 and until now assumed that as long as you are in version 0.* everything will be fine

**Comment by cgarciae** [comment]
Hey @nosmoke ! Thanks for reporting the issue. Fortunately this is a quite fix.

BTW: its a good practice to freeze dependencias (refer to exact versions) for production environments, check out tools like `poetry` or `pipenv` which helps you with this.

**Comment by cgarciae** [comment]
Fixed version `0.4.2` via #42
