### ISSUE TITLE
Split and merge?

### ISSUE THREAD

**Issue by ShakedDovrat** [cgarciae/pypeln#82]
I have two transformations (i.e. map operations) that need to apply to the same input, and I have a different transformation that needs the two outputs from the two previous transformations.

For this purpose, I would like a `split` functionality to send the same input to two different processes, and a `merge` functionality to read their different outputs and use as inputs of this final third transformation. The third transformation should wait for both inputs to arrive before it begins to process.
Of course, in general this could have more stages with several branches, multiway (more than 2) merges, etc. Also, not all branches might merge into one at the end of the pipeline.

Is there a way to achieve this currently? If not, are you planning to support such functionality?

Thank you.

**Comment by ShakedDovrat** [comment]
OK, I should have RTFM. I can split by sending a stage to two new stages, and merge using `concat`.
Nevermind.

**Comment by wxd** [comment]
@ShakedDovrat is there any chance you could share code samples? Please! Right now, I can't even figure out how to split without executing the parent twice.

My use case is the following: the main linear trunk of the pipeline sends multiple requests to an API that returns JSON arrays of objects (Stage 1), parses them into Python objects (Stage 2), and processes them further (Stages 3-...). I would like to branch out a stage after Stage 1 that just writes out raw JSON strings into files; this stage is completely unrelated to anything that happens in Stage 2 and further.

```
DOWNLOAD ---[str]---> PARSE ---[list of objects]---> PROCESS
          |
          |---> STORE
```

The current non-working approach looks a bit like this:
```python
def download(params) -> str:
    return requests.get(URL, params=params).text

def parse(json_str: str) -> Iterable[CustomClass]:
    objects: list[dict[str, Any]] = json.loads(json_str)
    for obj in objects:
        yield CustomClass.parse_dict(obj)

def store(json_str: str, element_index) - > Iterable[CustomClass]:
   with open(f"{element_index}.json", "w") as f:
        f.write(json_str)
    return tuple()  # Dummy output

def process(obj: CustomClass):
    return id(obj)  # for example

download_stage = pl.thread.map(download, PARAM_LIST, workers=1)
parse_stage = pl.sync.flat_map(parse, download_stage)
store_stage = pl.thread.flat_map(store, download_stage, workers=1)
process_stage = pl.sync.map(process)

pipeline = pl.sync.concat([parse_stage, store_stage]) | process_stage
for _ in pipeline:
    print(_)
```

`download_stage` gets built and executed twice.

**Comment by cgarciae** [comment]
Hey @ShakedDovrat, internally `pypeln` forms a DAG, `download_stage` will send its outputs to the Queues of both `parse_stage` and `store_stage`. It shouldn't run twice, if you are experiencing this behavior please open another issue reporting it as a bug.

**Comment by ShakedDovrat** [comment]
@wxd I didn't use pypeln in the end, so I'm afraid I can't help you.

**Comment by pg** [comment]
@ShakedDovrat Which other library/framework did you consider and use instead of pypeln?
