### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ktoprakucar** [cgarciae/pypeln#90]
**Describe the bug**

**Minimal code to reproduce**
Small snippet that contains a minimal amount of code.
```python

from pypeln import thread as th
        alis = List[AliBudget]

        api_responses = (
            th.from_iterable(alis)
            | th.map(self.__service.update, workers=10)
            | th.filter(lambda r: r is not None)
            | list
        )

```

**Expected behavior**
I am not sure it's bug-fixed later, but wanted share it with you. We use pypeln==0.1.9 to handle an update operation. Even we see the successful logs inside of update method, it returns None even it should return AliBudget object.

We also observe that thread even do not call update operation (we cannot see the first log of update method)

**Library Info**
pypeln==0.1.9

```python
from pypeln import thread as th
```

**Additional context**
As I mentioned above, briefly, threads do not return response or do not call the method. I tried check release notes after 0.1.9 but I could not find any similar fix/improvement. It might have been fixed.

**Comment by cgarciae** [comment]
Hey @ktoprakucar! In the current version of pypeln (`0.4.9)` the example below is working:

```python
from pypeln import thread as th

alis = [1, 2, None, 4, 5]

api_responses = (
    th.from_iterable(alis)
    | th.map(lambda x: x + 1 if x is not None else None, workers=3)
    | th.filter(lambda r: r is not None)
    | list
)

print(api_responses) # [2, 3, 5, 6]
```
